name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Find Docker Tag
      id: tagversion
      shell: bash
      run: |
        GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
        echo GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT
        echo "::set-output name=docker_tag::$GITHUB_SHA_SHORT"
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        IMAGE_NAME: sample-app
        DOCKERHUB_REPO: soumy2091/my-kube-pri-test
        # IMAGE_TAG: ${{ github.sha }}
        IMAGE_TAG: ${{ steps.tagversion.outputs.docker_tag }}
      run: |
        docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
        # docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG  
        docker push $DOCKER_USERNAME/my-kube-pri-test:$IMAGE_TAG
